global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # --- 1. Prometheus Monitoring (Самоконтроль) ---
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- 2. FastAPI Backend Monitoring ---
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']
